### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by vascopitaf**

### CODE REVIEW

**Comment by almereyda** [comment]
@gandhiano What do we need to do with this code? Will @ecobytes be in charge of running it?

**Comment by gandhiano** [comment]
Yes. Ecobytes is the formal partner for the social innovation prize we got with this project, and we had some funds reserved for providing the hosting.

**Comment by almereyda** [comment]
Many thanks @vascopitaf for your latest pushes!

Do you have a staging instance where we can check your latest work, and instructions on how we can build a production grade deployment from this? We'd preferably use Docker and Docker-Compose for this.

Feel free to join us in https://riot.allmende.io/#/room/#ecobytes-studios:matrix.allmende.io to discuss the next steps together.

**Comment by vascopitaf** [comment]
yout can just do 
 vagrant up
in branch Devel 

it uses:
 postgresql database
 php5.6.30,  
 php-fpm
 nginx 
 composer
 nginx-1.6.2

**Comment by almereyda** [comment]
Hi @vascopitaf does your merge mean the project is now finished? Usually and preferably the merge is only done after code review and by another person, to ensure peer review.

As far as I know Vagrant is a system only used for development environments. To bring this code live to the public, we need to create another environment as indicated above. This question was externalised into #9.

**Comment by vascopitaf** [comment]
ok. sorry

there was  a big green button for me to press.

the branch is still Devel. and not master
won't merge again.

i'm developing here:
https://github.com/vascopitaf/plantei.eu-website


i'm checking dokku. never used docker

**Comment by almereyda** [comment]
No need to revert the PR, but now that it's done, okay.

You are seeing the green button, since you are listed as a project maintainer in https://github.com/orgs/ecobytes/teams/plantei-eu

We have a Dokku instance at Ecobytes to play with. You can also come to https://riot.allmende.io/#/room/#ecobytes-studios:matrix.allmende.io and chat with us directly, if you have further questions.

**Pull request merged**
